// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL6Y2okjMbi3EcqrBnaE-ky-KvOF7hVA8',
    appId: '1:283818817351:web:d21c2a242b858cd84c3e62',
    messagingSenderId: '283818817351',
    projectId: 'trucki-database',
    authDomain: 'trucki-database.firebaseapp.com',
    storageBucket: 'trucki-database.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2bhNnHVJoA7GqgMX7ZLnZh3TmrETBb70',
    appId: '1:283818817351:android:1e75ed115c53de124c3e62',
    messagingSenderId: '283818817351',
    projectId: 'trucki-database',
    storageBucket: 'trucki-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmfHWs5gW0v7_mep4Y_uBIBw5Mo6W5LGw',
    appId: '1:283818817351:ios:d91761581f0b31b84c3e62',
    messagingSenderId: '283818817351',
    projectId: 'trucki-database',
    storageBucket: 'trucki-database.appspot.com',
    iosBundleId: 'com.example.restaurant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmfHWs5gW0v7_mep4Y_uBIBw5Mo6W5LGw',
    appId: '1:283818817351:ios:d91761581f0b31b84c3e62',
    messagingSenderId: '283818817351',
    projectId: 'trucki-database',
    storageBucket: 'trucki-database.appspot.com',
    iosBundleId: 'com.example.restaurant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL6Y2okjMbi3EcqrBnaE-ky-KvOF7hVA8',
    appId: '1:283818817351:web:7b1aecf2880bff4d4c3e62',
    messagingSenderId: '283818817351',
    projectId: 'trucki-database',
    authDomain: 'trucki-database.firebaseapp.com',
    storageBucket: 'trucki-database.appspot.com',
  );
}
